language: java
jdk:
  - oraclejdk8
  - oraclejdk7
install:
- wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
- tar xvzf aerospike-server.tgz
- cp -f .travis/aerospike.conf ./aerospike-server/share/etc
- cd aerospike-server
- sed -i -e 's/\${me}/"root"/' share/libexec/aerospike-start
- sed -i -e 's/set_shmmax$/#set_shmmax/' share/libexec/aerospike-start
- sed -i -e 's/set_shmall$/#set_shmall/' share/libexec/aerospike-start
- mkdir instance1
- ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
- cd instance1
- ./bin/aerospike start
- ../../scripts/wait-for-node.sh var/log/aerospike.log
- cd ../..
notifications:
  email:
  - qe-notices@aerospike.com
  hipchat:
    rooms:
      secure: H5qTvLxIBBinW4eE6D/x1+BBLUeOb+7dq3wkgSR8IUTGoBZ2bbVWwqNbKUJ1ueuKs4g9RvV7sDkG03dSze/lZJcE+bOMfIGkmBRl0InnTZdGvAs9QD2DCs6d+iNWBM9OvIPvjyTBJ2ryhmYcB2NFr2Nubl0xgdzFJA2BOAvHLK0=
  slack:
    secure: eTiZiYHWKgwzvR0VksJgaR3fOK4+HTT4vN+3N8/n4RUXAnzEEurvpAbwFwF0e47a5Pt1ro731Je/lgO6BXWsa8Cy/ZtuF/33VhKSaWsMopYfOcoGpGyc8GH3pz/7fnT9kz/f6ZSGpp+BV+hK8dYu3x5kKWCQ7VTq33CNEYLmcow=
